apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-web
  annotations:
    argocd.argoproj.io/sync-options: Validate=false 
spec:
  selector:
    matchLabels:
      app: cicd-web
  replicas: 1
  template:
    metadata:
      labels:
        app: cicd-web
    spec:
      containers:
        - name: cicd-web-container
          image: bluetic321/cicd-web:52
          ports:
            - containerPort: 8080

