apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-web
  annotations:
    argocd.argoproj.io/sync-options: Validate=false 
spec:
  selector:
    matchLabels:
      app: cicd-web
  #replicas: 2
  template:
    metadata:
      labels:
        app: cicd-web
    spec:
      containers:
        - name: cicd-web-container
          image: bluetic321/cicd-back:51
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"

