apiVersion: v1
kind: Service
metadata:
  name: cicd-web
  labels:
    app: cicd-web
  annotations:
    argocd.argoproj.io/sync-options: Validate=false

spec:
  type: ClusterIP
  selector:
    app: cicd-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

