apiVersion: v1
kind: Service
metadata:
  name: cicd-test
  labels:
    app: cicd-test
spec:
  type: ClusterIP
  selector:
    app: cicd-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

